### ISSUE TITLE
the private keys shown are invalid

### ISSUE THREAD

**Issue by AayushGoyal22** [Pymmdrza/LitecoinCracker#3]

**Comment by AayushGoyal22** [comment]
it says non base 58 character and when i convert it its not workingg, i think there is a problem in the script

**Comment by Pymmdrza** [comment]
> it says non base 58 character and when i convert it its not workingg, i think there is a problem in the script

https://colab.research.google.com/drive/1QRvE-rWTKS0Fia-MTHVrY2TPWhsJDWg-?usp=sharing
